# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mediamodal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='newsmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogModel',
        ),
        migrations.DeleteModel(
            name='MediaModal',
        ),
        migrations.DeleteModel(
            name='NewsModel',
        ),
    ]
