# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20171005_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='link_to_audo',
            new_name='link_to_audio',
        ),
        migrations.AlterField(
            model_name='audio',
            name='featured_image',
            field=models.FileField(upload_to='uploads/media/audio'),
        ),
    ]
