# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='link_to_audio',
            field=models.CharField(max_length=200),
        ),
    ]
