# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20171006_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='link_to_audio',
        ),
        migrations.AddField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='uploads/audio'),
        ),
    ]
