# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20171008_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
    ]
