# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20171008_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
