# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20171008_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
